name = "metricx-pixel"
type = "web_pixel_extension"
uid = "ac059931-d39c-639a-a5dd-78413a47fc86be80639f"

runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "enabled"

[settings]
type = "object"

[settings.fields.workspaceId]
name = "Workspace ID"
description = "Your Metricx workspace ID"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]

[settings.fields.apiEndpoint]
name = "API Endpoint"
description = "Metricx API endpoint"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]
